### ISSUE TITLE
Consume Tooling API directly from Buildship

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#207]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [donat](https://github.com/donat)**
_Monday Jan 09, 2017 at 15:22 GMT_

----

## Code review

- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Friday Jan 13, 2017 at 10:13 GMT_

----

Let's explode this story to smaller chunks.

**Comment by donat** [comment]
I've set up a the `remove-tooling-commons` feature branch for this epic.

**Comment by donat** [comment]
It's done!
