### ISSUE TITLE
Integrate with Kotlin Eclipse bundles

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#211]
<a href="https://github.com/etiennestuder"><img src="https://avatars.githubusercontent.com/u/231070?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [etiennestuder](https://github.com/etiennestuder)**
_Saturday May 21, 2016 at 18:23 GMT_

----

## Motivation

Whatever the title means in detail, as Kotlin is becoming a first-class citizen build language for Gradle, we will need to provide the ability to support Kotlin build code editing in Eclipse.

## Code review
- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).
